import numpy as np
import pandas as pd

#Extract
df=pd.read_csv("../DataWarehouse/DimCountry.csv",index_col=0)

#Transform - Enrich
country_to_region_continent = {
    'Afghanistan': ('South Asia', 'Asia'),
    'Albania': ('Europe', 'Europe'),
    'Algeria': ('North Africa', 'Africa'),
    'Andorra': ('Europe', 'Europe'),
    'Angola': ('Sub-Saharan Africa', 'Africa'),
    'Antigua and Barbuda': ('Latin America & Caribbean', 'North America'),
    'Argentina': ('Latin America & Caribbean', 'South America'),
    'Armenia': ('Central Asia', 'Asia'),
    'Australia': ('Oceania', 'Oceania'),
    'Austria': ('Europe', 'Europe'),
    'Azerbaijan': ('Central Asia', 'Asia'),
    'Bahamas': ('Latin America & Caribbean', 'North America'),
    'Bahrain': ('Middle East', 'Asia'),
    'Bangladesh': ('South Asia', 'Asia'),
    'Barbados': ('Latin America & Caribbean', 'North America'),
    'Belarus': ('Europe', 'Europe'),
    'Belgium': ('Europe', 'Europe'),
    'Belize': ('Latin America & Caribbean', 'North America'),
    'Benin': ('Sub-Saharan Africa', 'Africa'),
    'Bhutan': ('South Asia', 'Asia'),
    'Bolivia': ('Latin America & Caribbean', 'South America'),
    'Bosnia and Herzegovina': ('Europe', 'Europe'),
    'Botswana': ('Sub-Saharan Africa', 'Africa'),
    'Brazil': ('Latin America & Caribbean', 'South America'),
    'Brunei': ('Southeast Asia', 'Asia'),
    'Bulgaria': ('Europe', 'Europe'),
    'Burkina Faso': ('Sub-Saharan Africa', 'Africa'),
    'Burundi': ('Sub-Saharan Africa', 'Africa'),
    'Cabo Verde': ('Sub-Saharan Africa', 'Africa'),
    'Cambodia': ('Southeast Asia', 'Asia'),
    'Cameroon': ('Sub-Saharan Africa', 'Africa'),
    'Canada': ('North America', 'North America'),
    'Central African Republic': ('Sub-Saharan Africa', 'Africa'),
    'Chad': ('Sub-Saharan Africa', 'Africa'),
    'Chile': ('Latin America & Caribbean', 'South America'),
    'China': ('East Asia', 'Asia'),
    'Colombia': ('Latin America & Caribbean', 'South America'),
    'Comoros': ('Sub-Saharan Africa', 'Africa'),
    'Congo, Democratic Republic of the': ('Sub-Saharan Africa', 'Africa'),
    'Congo, Republic of the': ('Sub-Saharan Africa', 'Africa'),
    'Costa Rica': ('Latin America & Caribbean', 'North America'),
    'Croatia': ('Europe', 'Europe'),
    'Cuba': ('Latin America & Caribbean', 'North America'),
    'Cyprus': ('Europe', 'Europe'),
    'Czechia': ('Europe', 'Europe'),
    'Denmark': ('Europe', 'Europe'),
    'Djibouti': ('Sub-Saharan Africa', 'Africa'),
    'Dominica': ('Latin America & Caribbean', 'North America'),
    'Dominican Republic': ('Latin America & Caribbean', 'North America'),
    'Ecuador': ('Latin America & Caribbean', 'South America'),
    'Egypt': ('North Africa', 'Africa'),
    'El Salvador': ('Latin America & Caribbean', 'North America'),
    'Equatorial Guinea': ('Sub-Saharan Africa', 'Africa'),
    'Eritrea': ('Sub-Saharan Africa', 'Africa'),
    'Estonia': ('Europe', 'Europe'),
    'Eswatini': ('Sub-Saharan Africa', 'Africa'),
    'Ethiopia': ('Sub-Saharan Africa', 'Africa'),
    'Fiji': ('Oceania', 'Oceania'),
    'Finland': ('Europe', 'Europe'),
    'France': ('Europe', 'Europe'),
    'Gabon': ('Sub-Saharan Africa', 'Africa'),
    'Gambia': ('Sub-Saharan Africa', 'Africa'),
    'Georgia': ('Central Asia', 'Asia'),
    'Germany': ('Europe', 'Europe'),
    'Ghana': ('Sub-Saharan Africa', 'Africa'),
    'Greece': ('Europe', 'Europe'),
    'Grenada': ('Latin America & Caribbean', 'North America'),
    'Guatemala': ('Latin America & Caribbean', 'North America'),
    'Guinea': ('Sub-Saharan Africa', 'Africa'),
    'Guinea-Bissau': ('Sub-Saharan Africa', 'Africa'),
    'Guyana': ('Latin America & Caribbean', 'South America'),
    'Haiti': ('Latin America & Caribbean', 'North America'),
    'Honduras': ('Latin America & Caribbean', 'North America'),
    'Hungary': ('Europe', 'Europe'),
    'Iceland': ('Europe', 'Europe'),
    'India': ('South Asia', 'Asia'),
    'Indonesia': ('Southeast Asia', 'Asia'),
    'Iran': ('Middle East', 'Asia'),
    'Iraq': ('Middle East', 'Asia'),
    'Ireland': ('Europe', 'Europe'),
    'Israel': ('Middle East', 'Asia'),
    'Italy': ('Europe', 'Europe'),
    'Jamaica': ('Latin America & Caribbean', 'North America'),
    'Japan': ('East Asia', 'Asia'),
    'Jordan': ('Middle East', 'Asia'),
    'Kazakhstan': ('Central Asia', 'Asia'),
    'Kenya': ('Sub-Saharan Africa', 'Africa'),
    'Kiribati': ('Oceania', 'Oceania'),
    'Kuwait': ('Middle East', 'Asia'),
    'Kyrgyzstan': ('Central Asia', 'Asia'),
    'Laos': ('Southeast Asia', 'Asia'),
    'Latvia': ('Europe', 'Europe'),
    'Lebanon': ('Middle East', 'Asia'),
    'Lesotho': ('Sub-Saharan Africa', 'Africa'),
    'Liberia': ('Sub-Saharan Africa', 'Africa'),
    'Libya': ('North Africa', 'Africa'),
    'Liechtenstein': ('Europe', 'Europe'),
    'Lithuania': ('Europe', 'Europe'),
    'Luxembourg': ('Europe', 'Europe'),
    'Madagascar': ('Sub-Saharan Africa', 'Africa'),
    'Malawi': ('Sub-Saharan Africa', 'Africa'),
    'Malaysia': ('Southeast Asia', 'Asia'),
    'Maldives': ('South Asia', 'Asia'),
    'Mali': ('Sub-Saharan Africa', 'Africa'),
    'Malta': ('Europe', 'Europe'),
    'Marshall Islands': ('Oceania', 'Oceania'),
    'Mauritania': ('Sub-Saharan Africa', 'Africa'),
    'Mauritius': ('Sub-Saharan Africa', 'Africa'),
    'Mexico': ('North America', 'North America'),
    'Micronesia': ('Oceania', 'Oceania'),
    'Moldova': ('Europe', 'Europe'),
    'Monaco': ('Europe', 'Europe'),
    'Mongolia': ('East Asia', 'Asia'),
    'Montenegro': ('Europe', 'Europe'),
    'Morocco': ('North Africa', 'Africa'),
    'Mozambique': ('Sub-Saharan Africa', 'Africa'),
    'Myanmar (Burma)': ('Southeast Asia', 'Asia'),
    'Namibia': ('Sub-Saharan Africa', 'Africa'),
    'Nauru': ('Oceania', 'Oceania'),
    'Nepal': ('South Asia', 'Asia'),
    'Netherlands': ('Europe', 'Europe'),
    'New Zealand': ('Oceania', 'Oceania'),
    'Nicaragua': ('Latin America & Caribbean', 'North America'),
    'Niger': ('Sub-Saharan Africa', 'Africa'),
    'Nigeria': ('Sub-Saharan Africa', 'Africa'),
    'North Korea': ('East Asia', 'Asia'),
    'North Macedonia': ('Europe', 'Europe'),
    'Norway': ('Europe', 'Europe'),
    'Oman': ('Middle East', 'Asia'),
    'Pakistan': ('South Asia', 'Asia'),
    'Palau': ('Oceania', 'Oceania'),
    'Palestine State': ('Middle East', 'Asia'),
    'Panama': ('Latin America & Caribbean', 'North America'),
    'Papua New Guinea': ('Oceania', 'Oceania'),
    'Paraguay': ('Latin America & Caribbean', 'South America'),
    'Peru': ('Latin America & Caribbean', 'South America'),
    'Philippines': ('Southeast Asia', 'Asia'),
    'Poland': ('Europe', 'Europe'),
    'Portugal': ('Europe', 'Europe'),
    'Qatar': ('Middle East', 'Asia'),
    'Romania': ('Europe', 'Europe'),
    'Russia': ('Europe', 'Europe'),
    'Rwanda': ('Sub-Saharan Africa', 'Africa'),
    'Saint Kitts and Nevis': ('Latin America & Caribbean', 'North America'),
    'Saint Lucia': ('Latin America & Caribbean', 'North America'),
    'Saint Vincent and the Grenadines': ('Latin America & Caribbean', 'North America'),
    'Samoa': ('Oceania', 'Oceania'),
    'San Marino': ('Europe', 'Europe'),
    'Sao Tome and Principe': ('Sub-Saharan Africa', 'Africa'),
    'Saudi Arabia': ('Middle East', 'Asia'),
    'Senegal': ('Sub-Saharan Africa', 'Africa'),
    'Serbia': ('Europe', 'Europe'),
    'Seychelles': ('Sub-Saharan Africa', 'Africa'),
    'Sierra Leone': ('Sub-Saharan Africa', 'Africa'),
    'Singapore': ('Southeast Asia', 'Asia'),
    'Slovakia': ('Europe', 'Europe'),
    'Slovenia': ('Europe', 'Europe'),
    'Solomon Islands': ('Oceania', 'Oceania'),
    'Somalia': ('Sub-Saharan Africa', 'Africa'),
    'South Africa': ('Sub-Saharan Africa', 'Africa'),
    'South Korea': ('East Asia', 'Asia'),
    'South Sudan': ('Sub-Saharan Africa', 'Africa'),
    'Spain': ('Europe', 'Europe'),
    'Sri Lanka': ('South Asia', 'Asia'),
    'Sudan': ('Sub-Saharan Africa', 'Africa'),
    'Suriname': ('Latin America & Caribbean', 'South America'),
    'Sweden': ('Europe', 'Europe'),
    'Switzerland': ('Europe', 'Europe'),
    'Syria': ('Middle East', 'Asia'),
    'Taiwan': ('East Asia', 'Asia'),
    'Tajikistan': ('Central Asia', 'Asia'),
    'Tanzania': ('Sub-Saharan Africa', 'Africa'),
    'Thailand': ('Southeast Asia', 'Asia'),
    'Timor-Leste': ('Southeast Asia', 'Asia'),
    'Togo': ('Sub-Saharan Africa', 'Africa'),
    'Tonga': ('Oceania', 'Oceania'),
    'Trinidad and Tobago': ('Latin America & Caribbean', 'North America'),
    'Tunisia': ('North Africa', 'Africa'),
    'Turkey': ('Middle East', 'Asia'),
    'Turkmenistan': ('Central Asia', 'Asia'),
    'Tuvalu': ('Oceania', 'Oceania'),
    'Uganda': ('Sub-Saharan Africa', 'Africa'),
    'Ukraine': ('Europe', 'Europe'),
    'United Arab Emirates': ('Middle East', 'Asia'),
    'United Kingdom': ('Europe', 'Europe'),
    'United States': ('North America', 'North America'),
    'Uruguay': ('Latin America & Caribbean', 'South America'),
    'Uzbekistan': ('Central Asia', 'Asia'),
    'Vanuatu': ('Oceania', 'Oceania'),
    'Vatican City': ('Europe', 'Europe'),
    'Venezuela': ('Latin America & Caribbean', 'South America'),
    'Vietnam': ('Southeast Asia', 'Asia'),
    'Yemen': ('Middle East', 'Asia'),
    'Zambia': ('Sub-Saharan Africa', 'Africa'),
    'Zimbabwe': ('Sub-Saharan Africa', 'Africa')
}


df[['Region', 'Continent']] = df['country'].apply(
     lambda x: pd.Series(country_to_region_continent.get(x, (None, None))))

country_to_income = {
    'Afghanistan': 'Low income',
    'Albania': 'Upper-middle income',
    'Algeria': 'Lower-middle income',
    'Andorra': 'High income',
    'Angola': 'Lower-middle income',
    'Antigua and Barbuda': 'High income',
    'Argentina': 'Upper-middle income',
    'Armenia': 'Upper-middle income',
    'Australia': 'High income',
    'Austria': 'High income',
    'Azerbaijan': 'Upper-middle income',
    'Bahamas': 'High income',
    'Bahrain': 'High income',
    'Bangladesh': 'Lower-middle income',
    'Barbados': 'High income',
    'Belarus': 'Upper-middle income',
    'Belgium': 'High income',
    'Belize': 'Upper-middle income',
    'Benin': 'Lower-middle income',
    'Bhutan': 'Lower-middle income',
    'Bolivia': 'Lower-middle income',
    'Bosnia and Herzegovina': 'Upper-middle income',
    'Botswana': 'Upper-middle income',
    'Brazil': 'Upper-middle income',
    'Brunei': 'High income',
    'Bulgaria': 'Upper-middle income',
    'Burkina Faso': 'Low income',
    'Burundi': 'Low income',
    'Cabo Verde': 'Upper-middle income',
    'Cambodia': 'Lower-middle income',
    'Cameroon': 'Lower-middle income',
    'Canada': 'High income',
    'Central African Republic': 'Low income',
    'Chad': 'Low income',
    'Chile': 'High income',
    'China': 'Upper-middle income',
    'Colombia': 'Upper-middle income',
    'Comoros': 'Lower-middle income',
    'Congo, Democratic Republic of the': 'Low income',
    'Congo, Republic of the': 'Lower-middle income',
    'Costa Rica': 'High income',
    'Croatia': 'High income',
    'Cuba': 'Upper-middle income',
    'Cyprus': 'High income',
    'Czechia': 'High income',
    'Denmark': 'High income',
    'Djibouti': 'Lower-middle income',
    'Dominica': 'Upper-middle income',
    'Dominican Republic': 'Upper-middle income',
    'Ecuador': 'Upper-middle income',
    'Egypt': 'Lower-middle income',
    'El Salvador': 'Upper-middle income',
    'Equatorial Guinea': 'Upper-middle income',
    'Eritrea': 'Low income',
    'Estonia': 'High income',
    'Eswatini': 'Lower-middle income',
    'Ethiopia': 'Low income',
    'Fiji': 'Upper-middle income',
    'Finland': 'High income',
    'France': 'High income',
    'Gabon': 'Upper-middle income',
    'Gambia': 'Low income',
    'Georgia': 'Upper-middle income',
    'Germany': 'High income',
    'Ghana': 'Lower-middle income',
    'Greece': 'High income',
    'Grenada': 'Upper-middle income',
    'Guatemala': 'Upper-middle income',
    'Guinea': 'Lower-middle income',
    'Guinea-Bissau': 'Low income',
    'Guyana': 'High income',
    'Haiti': 'Lower-middle income',
    'Honduras': 'Lower-middle income',
    'Hungary': 'High income',
    'Iceland': 'High income',
    'India': 'Lower-middle income',
    'Indonesia': 'Upper-middle income',
    'Iran': 'Upper-middle income',
    'Iraq': 'Upper-middle income',
    'Ireland': 'High income',
    'Israel': 'High income',
    'Italy': 'High income',
    'Jamaica': 'Upper-middle income',
    'Japan': 'High income',
    'Jordan': 'Lower-middle income',
    'Kazakhstan': 'Upper-middle income',
    'Kenya': 'Lower-middle income',
    'Kiribati': 'Lower-middle income',
    'Kuwait': 'High income',
    'Kyrgyzstan': 'Lower-middle income',
    'Laos': 'Lower-middle income',
    'Latvia': 'High income',
    'Lebanon': 'Lower-middle income',
    'Lesotho': 'Lower-middle income',
    'Liberia': 'Low income',
    'Libya': 'Upper-middle income',
    'Liechtenstein': 'High income',
    'Lithuania': 'High income',
    'Luxembourg': 'High income',
    'Madagascar': 'Low income',
    'Malawi': 'Low income',
    'Malaysia': 'Upper-middle income',
    'Maldives': 'Upper-middle income',
    'Mali': 'Low income',
    'Malta': 'High income',
    'Marshall Islands': 'Upper-middle income',
    'Mauritania': 'Lower-middle income',
    'Mauritius': 'Upper-middle income',
    'Mexico': 'Upper-middle income',
    'Micronesia': 'Lower-middle income',
    'Moldova': 'Upper-middle income',
    'Monaco': 'High income',
    'Mongolia': 'Upper-middle income',
    'Montenegro': 'Upper-middle income',
    'Morocco': 'Lower-middle income',
    'Mozambique': 'Low income',
    'Myanmar (Burma)': 'Lower-middle income',
    'Namibia': 'Upper-middle income',
    'Nauru': 'High income',
    'Nepal': 'Lower-middle income',
    'Netherlands': 'High income',
    'New Zealand': 'High income',
    'Nicaragua': 'Lower-middle income',
    'Niger': 'Low income',
    'Nigeria': 'Lower-middle income',
    'North Korea': 'Low income',
    'North Macedonia': 'Upper-middle income',
    'Norway': 'High income',
    'Oman': 'High income',
    'Pakistan': 'Lower-middle income',
    'Palau': 'High income',
    'Panama': 'High income',
    'Papua New Guinea': 'Lower-middle income',
    'Paraguay': 'Upper-middle income',
    'Peru': 'Upper-middle income',
    'Philippines': 'Lower-middle income',
    'Poland': 'High income',
    'Portugal': 'High income',
    'Qatar': 'High income',
    'Romania': 'High income',
    'Russia': 'High income',
    'Rwanda': 'Low income',
    'Saint Kitts and Nevis': 'High income',
    'Saint Lucia': 'Upper-middle income',
    'Saint Vincent and the Grenadines': 'Upper-middle income',
    'Samoa': 'Lower-middle income',
    'San Marino': 'High income',
    'Sao Tome and Principe': 'Lower-middle income',
    'Saudi Arabia': 'High income',
    'Senegal': 'Lower-middle income',
    'Serbia': 'Upper-middle income',
    'Seychelles': 'High income',
    'Sierra Leone': 'Low income',
    'Singapore': 'High income',
    'Slovakia': 'High income',
    'Slovenia': 'High income',
    'Solomon Islands': 'Lower-middle income',
    'Somalia': 'Low income',
    'South Africa': 'Upper-middle income',
    'South Korea': 'High income',
    'South Sudan': 'Low income',
    'Spain': 'High income',
    'Sri Lanka': 'Lower-middle income',
    'Sudan': 'Low income',
    'Suriname': 'Upper-middle income',
    'Sweden': 'High income',
    'Switzerland': 'High income',
    'Syria': 'Low income',
    'Taiwan': 'High income',
    'Tajikistan': 'Lower-middle income',
    'Tanzania': 'Lower-middle income',
    'Thailand': 'Upper-middle income',
    'Timor-Leste': 'Lower-middle income',
    'Togo': 'Low income',
    'Tonga': 'Upper-middle income',
    'Trinidad and Tobago': 'High income',
    'Tunisia': 'Lower-middle income',
    'Turkey': 'Upper-middle income',
    'Turkmenistan': 'Upper-middle income',
    'Tuvalu': 'Upper-middle income',
    'Uganda': 'Low income',
    'Ukraine': 'Upper-middle income',
    'United Arab Emirates': 'High income',
    'United Kingdom': 'High income',
    'United States': 'High income',
    'Uruguay': 'High income',
    'Uzbekistan': 'Lower-middle income',
    'Vanuatu': 'Lower-middle income',
    'Venezuela': None,  # unclassified according to World Bank for 2024-2025 :contentReference[oaicite:1]{index=1}
    'Vietnam': 'Lower-middle income',
    'Yemen': 'Low income',
    'Zambia': 'Lower-middle income',
    'Zimbabwe': 'Lower-middle income',
}

df['IncomeGroup']=df['country'].apply(
    lambda x : pd.Series(country_to_income.get(x,(None)))
)

def get_development_status(country):
    developed_countries = [
        'United States', 'Canada', 'United Kingdom', 'Germany', 'France', 'Italy', 
        'Japan', 'Australia', 'New Zealand', 'Austria', 'Belgium', 'Denmark', 
        'Finland', 'Ireland', 'Luxembourg', 'Netherlands', 'Norway', 'Sweden', 
        'Switzerland', 'Iceland', 'Spain', 'Portugal', 'Greece', 'South Korea', 
        'Singapore', 'Israel', 'Slovenia', 'Czechia', 'Estonia', 'Slovakia', 
        'Lithuania', 'Latvia', 'Hungary', 'Poland', 'Croatia', 'Malta', 'Cyprus'
    ]
    
    least_developed_countries = [
        'Afghanistan', 'Angola', 'Bangladesh', 'Benin', 'Bhutan', 'Burkina Faso', 
        'Burundi', 'Cambodia', 'Central African Republic', 'Chad', 'Comoros', 
        'Congo, Democratic Republic of the', 'Djibouti', 'Eritrea', 'Ethiopia', 
        'Gambia', 'Guinea', 'Guinea-Bissau', 'Haiti', 'Kiribati', 'Laos', 'Lesotho', 
        'Liberia', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mozambique', 
        'Myanmar (Burma)', 'Nepal', 'Niger', 'Rwanda', 'Sao Tome and Principe', 
        'Senegal', 'Sierra Leone', 'Solomon Islands', 'Somalia', 'South Sudan', 
        'Sudan', 'Tanzania', 'Timor-Leste', 'Togo', 'Tuvalu', 'Uganda', 'Vanuatu', 
        'Yemen', 'Zambia'
    ]
    
    if country in developed_countries:
        return 'Developed'
    elif country in least_developed_countries:
        return 'Least Developed'
    else:
        return 'Developing'  

df['DevelopmentStatus'] = df['country'].apply(get_development_status)


#Filter
df=df[df.index.isin(['USA','CHN','JPN','DEU','IND','GBR','FRA','ITA','CAN','BRA','RUS','KOR','AUS','ESP','MEX','IDN','NLD','SAU','TUR','CHE','TWN','POL','SWE','BEL','THA'])]


#Load
df.to_csv("../DataWarehouse/DimCountry.csv")